### PR TITLE
VMNetworkAdapter: fix some issues on NetworkSetting parameter

### LINKED ISSUE #190: VMNetworkAdapter: Multiple DNS IP adresses does not work (parameter type need to be changed)
Hello, thanks for this code as it is very uncommon to have something functional for hyperv... 

#### Details of the scenario you tried and the problem that is occurring

When you try to provide a table in the networkingsetting object it does not work as parameter of function is String and not Tab String  (MSFT_xVMNetworkAdapter.psm1#L648 )
#### Verbose logs showing the problem
 "module_version": "3.17.0.0",
    "msg": "Failed to invoke DSC Set method: Incorrect function. ",
    "reboot_required": false,
    "verbose_set": [
        "Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = ResourceSet,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.",
        "An LCM method call arrived from computer HOST with user sid S-1-5-21-203002872-2615672331-1556995904-17199.",
        "[LY-C3-HOST3]: LCM:  [ Start  Set      ]  [[xVMNetworkAdapter]DirectResourceAccess]",
        "[LY-C3-HOST3]:                            [[xVMNetworkAdapter]DirectResourceAccess] Getting VM Network Adapter information.",
        "[LY-C3-HOST3]:                            [[xVMNetworkAdapter]DirectResourceAccess] Adding VM Network Adapter.",
        "[LY-C3-HOST3]: LCM:  [ End    Set      ]  [[xVMNetworkAdapter]DirectResourceAccess]  in 1.7500 seconds.",
        "Operation 'Invoke CimMethod' complete.",
        "Time taken for configuration job to complete is 1.906 seconds"

#### Suggested solution to the issue
Change parameter type to "String[]"
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
"item": {
        "NetworkSetting": {
            "DefaultGateway": "172.99.0.1",
            "DnsServer": "@("172.99.3.22", "172.993.2")",
            "IpAddress": "172.99.3.16",
            "Subnet": "255.255.0.0"
        },
        "name": "default",
        "switchname": "test",
        "vlanid": "15"
    },

We also tried multiple setting : 
"DnsServer": ["172.99.3.22", "172.99.3.2"],
"DnsServer": ("172.99.3.22", "172.99.3.2"),
"DnsServer": "172.99.3.22, 172.99.3.2",
```

#### The operating system the target node is running
Not related to operating system

#### Version and build of PowerShell the target node is running
<!--
    To help with this information, please run this command:
    $PSVersionTable
-->
[HOST]: PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.3866
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.3866
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used
ansible.windows.win_dsc 
This plugin is part of the ansible.windows collection (version 1.7.2).

Thanks for your help and fix !

### LINKED ISSUE #203: VMNetworkAdapter: Rename embedded instance class
The embedded instance class should be renamed to `VMNetworkAdapterNetworkSettings` to avoid any conflicts with other resources that could have an embedded instance with the same name.

https://github.com/dsccommunity/HyperVDsc/blob/b0397fbd78cb78589ff3b6e43120b170a8ce2875/source/DSCResources/DSC_VMNetworkAdapter/DSC_VMNetworkAdapter.schema.mof#L2

### LINKED ISSUE #204: VMNetworkAdapter: Should be able to ignore network settings
Should we also add a property `Dhcp` in the schema class `NetworkSettings` so we can easily determine if DHCP or static IP should be used? That I think would cover the scenarios:

- If `NetworkSettings` parameter is not part of configuration, do not enforce IP (DHCP or Static).
- If `NetworkSettings` parameter is passed
  - and contain `DHCP -eq $true` then enable DHCP.
  - and contain `DHCP -eq $false` then use Static IP.

Since we have renamed the resources and are releasing the module as a new major version we can also add this as a breaking change. 

_Originally posted by @johlju in https://github.com/dsccommunity/HyperVDsc/issues/189#issuecomment-1152918535_

### PR DESCRIPTION
**Pull request by stehlih**
#### Pull Request (PR) description

Fix some issues on NetworkSetting parameter

#### This Pull Request (PR) fixes the following issues

- Fixes #204
- Fixes #203
- Fixes #190

#### Task list

- [X] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [X] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [X] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [X] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/hypervdsc/205)

### CODE REVIEW

**Comment by stehlih** [comment]
I don‘t know what I must do here to solve this Codecov Report error.

**Comment by johlju** [comment]
Is is because no coverage report has been uploaded from when main-branch built. You can ignore it.

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/hypervdsc/205)* status: all files reviewed, 3 unresolved discussions (waiting on @stehlih)

___
*[`CHANGELOG.md` line 21 at r1](https://reviewable.io/reviews/dsccommunity/hypervdsc/205#-N76MGL-DEyPpznJqQkA:-N76MGL-DEyPpznJqQkB:b-ffwnd1) ([raw file](https://github.com/dsccommunity/hypervdsc/blob/9894a4996eb1414e4055011d0f6b645094858ade/CHANGELOG.md#L21)):*
> ```Markdown
>     in the GitHub Wiki documentation and conceptual help.
>   - VMNetworkAdapter
>     - Rename embedded instance class #203
> ```

We should add `BREAKING CHANGE:` to this entry as it is a breaking change for existing configurations.



_Code quote:_
```Markdown
- Rename embedded instance class #203
```
___
*[`source/DSCResources/DSC_VMNetworkAdapter/DSC_VMNetworkAdapter.psm1` line 659 at r1](https://reviewable.io/reviews/dsccommunity/hypervdsc/205#-N76LtkB4G2RXjCLjmJZ:-N76LtkC35_Ega9-sh7p:buze4v) ([raw file](https://github.com/dsccommunity/hypervdsc/blob/9894a4996eb1414e4055011d0f6b645094858ade/source/DSCResources/DSC_VMNetworkAdapter/DSC_VMNetworkAdapter.psm1#L659)):*
> ```PowerShell
>         [Parameter(ParameterSetName = 'Static')]
>         [System.String[]]
>         $DnsServers
> ```

We should keep the name `DnsServer` because named parameters should use singular. Throughout code and examples.



_Suggestion:_
```PowerShell
$DnsServer
```
___
*[`source/DSCResources/DSC_VMNetworkAdapter/DSC_VMNetworkAdapter.schema.mof` line 8 at r1](https://reviewable.io/reviews/dsccommunity/hypervdsc/205#-N76LMr-8N9dWSegS81p:-N76LMr-8N9dWSegS81q:b3jjq7) ([raw file](https://github.com/dsccommunity/hypervdsc/blob/9894a4996eb1414e4055011d0f6b645094858ade/source/DSCResources/DSC_VMNetworkAdapter/DSC_VMNetworkAdapter.schema.mof#L8)):*
> ```
>   [Write, Description("Subnets configured on the network adapter within the guest operating system.")] string Subnet;
>   [Write, Description("Default IP gateways configured on the network adapter within the guest operating system.")] string DefaultGateway;
>   [Write, Description("DNS servers configured on the network adapter within the guest operating system.")] string DnsServers[];
> ```

We should keep the name `DnsServer` because named parameters should use singular. The description can be changed to say it can be one or more IP addresses. Throughout code, tests, and examples.



_Suggestion:_
```
DnsServer[]
```

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/hypervdsc/205#-:-N7CDFXe2N2rmSr7-jxn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stehlih)

**Pull request merged**
