### PR TITLE
xVMSwitch: Adding new capability to enable Iov on the virtual switch

### LINKED ISSUE #165: xHyper-V: should support IovEnabled property
#### Details of the scenario you tried and the problem that is occurring
vSwitch can not be created with the IovEnabled property set to true using this resource

#### Verbose logs showing the problem
N/A - New capability not currently included in this resource

#### Suggested solution to the issue
When creating the vSwitch, a new boolean param should be added ($EnableIov)
If true, new-vmswitch command e.g.
New-VMSwitch **-EnableIov $true**

if $false or not specified, no modification to the new-vmswitch in the set is necessary

this can be tested by validating the value of (Get-VMSwitch -Name <switchName>).IovEnabled

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A - New capability not currently included in this resource

#### The operating system the target node is running
Windows Server 2016 or Windows Server 2019

#### Version and build of PowerShell the target node is running
N/A

#### Version of the DSC module that was used ('dev' if using current dev branch)
Master

### PR DESCRIPTION
**Pull request by dcuomo**
#### Pull Request (PR) description
This PR enables a new IovEnabled capability to resolve Issue #165.  IovEnabled is required for advanced scenarios like Guest RDMA.  It is also a virtual switch best practice (according to MSFT Networking team) to create the virtual switch with IovEnabled $true e.g. New-VMSwitch -EnableIov $true (note: the property on the VMSwitch is IovEnabled however the parameter to create the VMSwitch is -EnableIov)

#### This Pull Request (PR) fixes the following issues
- Fixes #165 

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [X] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/hypervdsc/166)

### CODE REVIEW

**Comment by dcuomo** [comment]
Hi @bgelens  - 

From the output in the failing tests, there's only one that I believe my changes would have affected (**Should run without exception while re-creating the VMSwitch**).  Is there a hint you could give as to why the bandwidth reservation tests are failing?

I'm also having difficulty reviewing why the Mock for VMSwitch is failing **A parameter cannot be found that matches parameter name 'EnableIov'** at C:\projects\xhyper-v\Tests\Unit\MSFT_xVMSwitch_Id.Tests.ps1: line 265 - I've verified that the resource works on a local system.  Is this a test failure that would need to be updated?  Appreciate the help...

I'm fine changing the default for Iov to false.  It is our best practice albeit not yet documented because it's destructive to fix it later and there's no negative to enabling it.  This is a legacy design that has not been updated in the cmdlet.

**Comment by bgelens** [comment]
When I find some time I'll see if I can help you pinpoint the issues. Hopefully somewhere this week

**Comment by bgelens** [comment]
I was able to have all test errors resolved:

I found that MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1 should be updated at line [86](https://github.com/dcuomo/xHyper-V/blob/dev/Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1#L86). I got the test to pass by having the hashtable look like:

```powershell
$mockedVMSwitch = @{
    Name = $Name
    SwitchType = 'External'
    AllowManagementOS = $AllowManagementOS
    NetAdapterInterfaceDescription = 'Microsoft Network Adapter Multiplexor Driver'
    IovEnabled = $false
}
```

MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1 should be updated at line [300](https://github.com/dcuomo/xHyper-V/blob/dev/Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1#L300) to pass the tests.  I got the test to pass by having the hashtable look like:

```powershell
$global:mockedVMSwitch = @{
    Name = "TestSwitch"
    SwitchType = "External"
    AllowManagementOS = $true
    EmbeddedTeamingEnabled = $true
    Id = [Guid]::NewGuid()
    NetAdapterInterfaceDescriptions = @("Microsoft Network Adapter Multiplexor Driver #1", "Microsoft Network Adapter Multiplexor Driver #2")
    IovEnabled = $false
}
```

MSFT_xVMSwitch_Id.Tests.ps1 should be updated at line [79](https://github.com/dcuomo/xHyper-V/blob/dev/Tests/Unit/MSFT_xVMSwitch_Id.Tests.ps1#L79) and [147](https://github.com/dcuomo/xHyper-V/blob/dev/Tests/Unit/MSFT_xVMSwitch_Id.Tests.ps1#L147) to pass the tests.

At line 79 a hashtable update should look like this:

```powershell
$mockedVMSwitch = @{
    Name                            = $Name
    SwitchType                      = 'External'
    AllowManagementOS               = $true
    EmbeddedTeamingEnabled          = $true
    LoadBalancingAlgorithm          = 'HyperVPort'
    BandwidthReservationMode        = 'Default'
    NetAdapterInterfaceDescriptions = @("Microsoft Network Adapter Multiplexor Driver #1", "Microsoft Network Adapter Multiplexor Driver #2")
    IovEnabled                      = $false
}
```

At line 147, an additional parameter should be included:

```powershell
Param(
    [Parameter()]
    [String]
    $Name,

    [Parameter()]
    [String[]]
    $NetAdapterName,

    [Parameter()]
    [String]
    $MinimumBandwidthMode,

    [Parameter()]
    [bool]
    $AllowManagementOS,

    [Parameter()]
    [String]
    $SwitchType,

    [Parameter()]
    [bool]
    $EnableEmbeddedTeaming,

    [Parameter()]
    [Guid]
    $Id,

    [Parameter()]
    [Boolean]
    $EnableIov
)
```

Hope you have enough info to continue working on your PR :) I will expect some additional tests to be included with the PR as well to validate the newly implemented logic (code paths, expected results).

On a side note: I found that at line [289](https://github.com/dcuomo/xHyper-V/blob/dev/DSCResources/MSFT_xVMSwitch/MSFT_xVMSwitch.psm1#L289) of MSFT_xVMSwitch.psm1 some style issues are present which should be fixed as well.

Current:

```powershell
If ($switch.IovEnabled -ne $IovEnabled) {
    Write-Verbose -Message ($LocalizedData.IovEnabledIncorrect -f $Name)
    $removeReaddSwitch = $true
}
```

Should look like:

```powershell
if ($switch.IovEnabled -ne $IovEnabled)
{
    Write-Verbose -Message ($LocalizedData.IovEnabledIncorrect -f $Name)
    $removeReaddSwitch = $true
}
```

Please note that I did not validate your actual contribution to be correct yet. I need a clean test result to start doing that.

If you need more help, please reach out!

**Comment by bgelens** [comment]
I'm not sure, is this ready for review now? If so, could you add some tests for your new functionality and update the changelog please

**Comment by dcuomo** [comment]
I implemented your recommendations and it passed all checks - Please review.  I'll update the changelog.

**Comment by bgelens** [comment]
Thanks for all the hard work! Please see the comments I made.

Could you also include some tests to verify the logic you introduced is working as expected?

**Comment by johlju** [comment]
We have renamed the resource, removing 'x', so please rebase this PR.

**Pull request closed without merging**
