### PR TITLE
VMNetworkAdapter: add parameter IgnoreNetworkSetting

### PR DESCRIPTION
**Pull request by stehlih**
#### Pull Request (PR) description

xVMNetworkAdapter: add parameter IgnoreNetworkSetting

Set the new parameter to `True` if the guest operating system configures the network adapter.
In this case all ip settings including DHCP are skipped.
The paramter is set to `False` as default to keep the current behavior.

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/hypervdsc/189)

### CODE REVIEW

**Comment by johlju** [comment]
We have renamed the resource, removing 'x', so please rebase this PR.

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/hypervdsc/189)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @johlju and @stehlih)

*[a discussion](https://reviewable.io/reviews/dsccommunity/hypervdsc/189#-N475UiB8vKnKncJSwcf:-N475UiB8vKnKncJSwcg:b-wklx93) (no related file):*
Looking at this change i thinking that adding a property for `IgnoreNetworkSetting` is not the right move. Would it not be better to refactor the resource to not enforce the existing property `NetworkSetting` if is is not specified in the configuration. if `$PSBoundParameters.ContainsKey('NetworkSetting')` then the resource should enforce (test and set) the property.

___

**Comment by johlju** [comment]
@stehlih let me know if my suggestion in the review comment does not work?

**Comment by stehlih** [comment]
Your proposal is the best way but it changes the current behavior of the resource and DHCP will not enabled explicitly if the NetworkSettings parameter is not specified (-> this was an unexpected behavior for me because it had have some side effects on my guest VM). 
I can make the code changes in the next 2 weeks and update my pull request.

**Comment by johlju** [comment]
Happy to see the changes. 

Should we also add a property `Dhcp` in the schema class `NetworkSettings` so we can easily determine if DHCP or static IP should be used? That I think would cover the scenarios:

- If `NetworkSettings` parameter is not part of configuration, do not enforce IP (DHCH or Static).
- If `NetworksSettings` parameter is passed
  - and contain `DHCP -eq $true` then enable DHCP.
  - and contain `DHCP -eq $false` then use Static IP.

Since we have renamed the resources and are releasing the module as a new major version we can also add this as a breaking change. 

I will wait for the updated PR. Many thanks and great work @stehlih! 🙇‍♂️

**Comment by johlju** [comment]
When this PR is reworked according to previous comment I think it will also close the issue #191, but would be great to aa a tgest with the set of parameter as seen in the issue.

**Comment by johlju** [comment]
FYI when rebasing. The resource and parameter descriptions has been removed from the README.md and moved to the schema.mof - the parameter descriptions are automatically generated for the WIki dokcumentation using the schema.mof and the resource's README.md.

**Pull request closed without merging**
