### PR TITLE
Update DSC_VMSwitch.psm1

### PR DESCRIPTION
**Pull request by gplenty**
#### Pull Request (PR) description

Changing the script to use GUID as opposed to the interface description, seems more beneficial

#### This Pull Request (PR) fixes the following issues 

As mentioned in the issue https://github.com/dsccommunity/HyperVDsc/issues/217

#### Task list

- [ ] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/HyperVDsc/218)

### CODE REVIEW

**Comment by johlju** [comment]
Please update the unit tests, and the change log.

Tests failing:
https://dev.azure.com/dsccommunity/HyperVDsc/_build/results?buildId=8562&view=logs&j=8af7cf9c-43a1-584d-6f5c-57bad8880974&t=a93ba588-7f3e-5259-6924-3f054a327451&l=776

**Comment by gplenty** [comment]
Have been able to get most of the failed items to clear, whilst still retaining parts of my original input to the DSC Resource DSC_VMSwitch.psm1

But for now I'm still waiting for the status to be reported on the last 4 expected checks.

**Comment by gplenty** [comment]
@johlju - I have to confess this is my first time ever I've uploaded anything to GitHub, created an Issue and Pull Request. So I'm pretty much learning as we go along in this process. 

In relation to how the tests scripts, rely still on the InterfaceDescription I rewrote my modifications to include query based upon the Interface Descriptions in an initial try { }, changing the ErrorAction to Stop as opposed to SilentlyContinue and then also included my modifications, so that we can still retrieve the Interface names from the vSwitch0, even if the Interface Descriptions differ between what is being shown in the Get-vSwitch output and the Get-NetAdapter output. 

Last night I updated the two scripts DSC_VMSwitch.psm1 and also the DSC_VMHost_set.config.ps1 as this still contained a mention of Import-DscResource -ModuleName 'xHyper-V' and having re-checked the status I can see that it's still stuck on "Some checks haven't completed yet"

dsccommunity.HyperVDsc (Build Package Module) Expected — Waiting for status to be reported
Required
dsccommunity.HyperVDsc (Test HQRM) Expected — Waiting for status to be reported
Required
dsccommunity.HyperVDsc (Test Integration) Expected — Waiting for status to be reported
Required
dsccommunity.HyperVDsc (Test Unit) Expected — Waiting for status to be reported
Required

How should I now proceed ?

**Comment by johlju** [comment]
Thank you for contributing! Not sure why the pipeline didn't run automatically.

**Comment by gplenty** [comment]
I'll close this pull request - and we'll now focus on trying to fix the hosts themselves, as it appears to only on certain hosts with QLogic BCM57810 or QLogic BCM57800, so it's only a small fraction of hosts.

**Pull request closed without merging**
